package lab8p2_hectorflores;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.AncestorListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;

public class WIN extends javax.swing.JFrame {

    /**
     * Creates new form WIN
     */
    public WIN() {
        initComponents();
        this.setLocationRelativeTo(null);
        setAll();
        boxActions();
        arbolHandler=new Arbol(jTree1);
        //jTreeActions();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoCB = new javax.swing.JComboBox<>();
        orderCB = new javax.swing.JComboBox<>();
        cutBTN = new javax.swing.JButton();
        copyBTN = new javax.swing.JButton();
        pasteBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        displayPAN = new javax.swing.JPanel();
        editCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cutBTN.setText("Cut");
        cutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutBTNActionPerformed(evt);
            }
        });

        copyBTN.setText("Copy");
        copyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyBTNActionPerformed(evt);
            }
        });

        pasteBTN.setText("Paste");
        pasteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteBTNActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTree1);

        javax.swing.GroupLayout displayPANLayout = new javax.swing.GroupLayout(displayPAN);
        displayPAN.setLayout(displayPANLayout);
        displayPANLayout.setHorizontalGroup(
            displayPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        displayPANLayout.setVerticalGroup(
            displayPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(displayPAN);

        editCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        editCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCBActionPerformed(evt);
            }
        });

        jLabel1.setText("Nuevo:");

        jLabel2.setText("...");

        jLabel3.setText("Ordenar por:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nuevoCB, javax.swing.GroupLayout.Alignment.LEADING, 0, 110, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(copyBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pasteBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderCB, 0, 110, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editCB, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cutBTN)
                    .addComponent(copyBTN)
                    .addComponent(pasteBTN)
                    .addComponent(editCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutBTNActionPerformed
        //funciones de cortar
    }//GEN-LAST:event_cutBTNActionPerformed

    private void copyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyBTNActionPerformed
        //funciones de copiar
    }//GEN-LAST:event_copyBTNActionPerformed

    private void pasteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteBTNActionPerformed
        //funciones de pegar
    }//GEN-LAST:event_pasteBTNActionPerformed

    private void editCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCBActionPerformed
        
    }//GEN-LAST:event_editCBActionPerformed

    private Arbol arbolHandler;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WIN().setVisible(true);
            }
        });
    }
    
    void setAll(){
        setBoxes();
    }
    
    void setBoxes(){
        orderCB.removeAllItems();
        orderCB.addItem("Nombre");
        orderCB.addItem("Fecha");
        orderCB.addItem("Tipo");
        orderCB.addItem("Tamano");
        
        nuevoCB.removeAllItems();
        nuevoCB.addItem("Carpeta");
        nuevoCB.addItem("Archivo");
        
        editCB.removeAllItems();
        editCB.addItem("Cambiar Nombre");
        editCB.addItem("Editar Archivo");
    }

    void boxActions(){
        //ORDER COMBO BOX
        orderCB.addActionListener(new ActionListener(){
            @Override
        public void actionPerformed(ActionEvent e){
            String selectedOption=(String) orderCB.getSelectedItem();
            if(selectedOption.equals("Nombre")){
                //Ordenar por NOMBRE
            }else if(selectedOption.equals("Fecha")){
                //Ordenar por FECHA
            }else if(selectedOption.equals("Tipo")){
                //Ordenar por TIPO
            }else if(selectedOption.equals("Tamano")){
                //Ordenar por TAMAÑO
            }
        }
        });
        
        
        //NUEVO COMBO BOX
        nuevoCB.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String selectedOption =(String) nuevoCB.getSelectedItem();
            if (selectedOption.equals("Archivo")) {
                String fileName = JOptionPane.showInputDialog(null, "Enter file name:");
                if (fileName != null && !fileName.isEmpty()) {
                    //usar en nombre fileName para crear nuevo archivo
                }
            } else if (selectedOption.equals("Carpeta")) {
                String folderName = JOptionPane.showInputDialog(null, "Enter folder name:");
                if (folderName != null && !folderName.isEmpty()) {
                    //usar el nombre folderName JOptionPane para crear nuevo folder
                }
            }
        }
    });
        
       //EDIT COMBO  BOX
       editCB.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
               String selectedOption=(String)editCB.getSelectedItem();
               if(selectedOption.equals("Cambiar Nombre")){
                   //Funcioambio de nombre de carpeta o archivo seleccionado
               }else if(selectedOption.equals("Editar Archivo")){
                   //Funciones de editar archivo
               }
           }
       }
       );    
    }
    
    /*
    void jTreeActions(){
         jTree1.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 2) {
                TreePath selectedPath = jTree1.getSelectionPath();
                DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) selectedPath.getLastPathComponent();
                File selectedFile = (File) selectedNode.getUserObject();

                if (selectedFile.isDirectory()) {
                    displayPAN.removeAll();

                    File[] files = selectedFile.listFiles();
                    if (files != null) {
                        for (File file : files) {
                            JLabel fileLabel = new JLabel(file.getName());
                            displayPAN.add(fileLabel);
                        }
                    }

                    displayPAN.revalidate();
                    displayPAN.repaint();
                }
            }
        }
    });
    }
    */
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton copyBTN;
    private javax.swing.JButton cutBTN;
    private javax.swing.JPanel displayPAN;
    private javax.swing.JComboBox<String> editCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    private javax.swing.JComboBox<String> nuevoCB;
    private javax.swing.JComboBox<String> orderCB;
    private javax.swing.JButton pasteBTN;
    // End of variables declaration//GEN-END:variables
}
